= SMART COSMOS Extension Playground
SMARTRAC Technology Fletcher Inc <api@smartrac-group.com>
:version: 3.0.0-SNAPSHOT
ifdef::env-github[:USER: SMARTRACTECHNOLOGY]
ifdef::env-github[:REPO: smartcosmos-ext-playground]
ifdef::env-github[:BRANCH: master]

image::https://travis-ci.org/{USER}/{REPO}.svg?branch={BRANCH}[Build Status, link=https://travis-ci.org/{USER}/{REPO}]
image::https://david-dm.org/{USER}/{REPO}/status.svg[Dependency Status, link=https://david-dm.org/{USER}/{REPO}#info=dependencies]
image::https://david-dm.org/{USER}/{REPO}/dev-status.svg[devDependency Status, link=https://david-dm.org/{USER}/{REPO}#info=devDependencies]

An extremely basic UI that leverages some of the Objects v3 endpoints with a more user-friendly UI component.

# Quick Start

[source,bash,subs="attributes,verbatim"]
----
# clone the repo
$ git clone https://github.com/{USER}/{REPO}.git {REPO}

# change directory to your app
$ cd {REPO}

# install the dependencies with npm
$ npm install

# start the server
$ npm start
----

go to http://localhost:8080 in your browser.

# Getting Started

## Dependencies

What you need to run this app:
* `node` and `npm` (Use https://github.com/creationix/nvm[NVM])
* Ensure you're running Node (`v4.1.x`+) and NPM (`2.14.x`+)

## Installing

* `clone` the repo
* `npm install` to install all dependencies

## Running the app

After you have installed all dependencies you can now run the app with:

```bash
npm start
```

It will start a local server using `webpack-dev-server` which will watch, build (in-memory), and reload for you. The port will be displayed to you as `http://localhost:8080`.

## Developing

### Add new components, services, pipes with Angular 2 cli

* `npm install -g angular-cli` to install Angular 2 cli
* Add a new component with: `ng generate component my-new-component`
* Add a new service with: `ng generate service my-new-service`
* Add a new pipe with: `ng generate pipe my-new-pipe`

Read more at https://github.com/angular/angular-cli[angular-cli github].

### Build files

* single run: `npm run build`
* build files and watch: `npm run watch`

## Testing

#### 1. Unit Tests

* single run: `npm test`
* live mode (TDD style): `npm run test-watch`

#### 2. End-to-End Tests (aka. e2e, integration)

* single run:
  * in a tab, *if not already running!*: `npm start`
  * in a new tab: `npm run webdriver-start`
  * in another new tab: `npm run e2e`
* interactive mode:
  * instead of the last command above, you can run: `npm run e2e-live`
  * when debugging or first writing test suites, you may find it helpful to try out Protractor commands without starting up the entire test suite. You can do this with the element explorer.
  * you can learn more about https://github.com/angular/protractor/blob/master/docs/debugging.md#testing-out-protractor-interactively[Protractor Interactive Mode here]

## Documentation

You can generate api docs (using http://typedoc.io/[TypeDoc]) for your code with the following:
```bash
npm run docs
```

# FAQ

#### Do I need to add script / link tags into index.html ?

No, Webpack will add all the needed Javascript bundles as script tags and all the CSS files as link tags. The advantage is that you don't need to modify the index.html every time you build your solution to update the hashes.

#### How to include external angular 2 libraries ?

It's simple, just install the lib via npm and import it in your code when you need it. Don't forget that you need to configure some external libs in the link:/src/bootstrap.ts[bootstrap] of your application.

### How to include external css files such as bootstrap.css ?

Just install the lib and import the css files in link:src/vendor.ts[vendor.ts]. For example this is how to do it with bootstrap:

```sh
npm install bootstrap@4.0.0 --save-dev
```

And in link:src/vendor.ts[vendor.ts] add the following:

```ts
import 'bootstrap/scss/bootstrap-flex';
```

# TypeScript

NOTE: To take full advantage of TypeScript with autocomplete you would have to use an editor with the correct TypeScript plugins.

## Use a TypeScript-aware editor

We have good experience using these editors:

* https://code.visualstudio.com/[Visual Studio Code]
* https://www.jetbrains.com/webstorm/download/[Webstorm 11+]
* https://atom.io/[Atom] with https://atom.io/packages/atom-typescript[TypeScript plugin] and https://atom.io/packages/linter-tslint[linter-tslint]
* http://www.sublimetext.com/3[Sublime Text] with https://github.com/Microsoft/Typescript-Sublime-plugin#installation[Typescript-Sublime-Plugin]

# License

link:/LICENSE[Apache-2.0]
